// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPzCBiuyilPcOOTYu6kmscs1Qwu2GaegE',
    appId: '1:183461530338:web:c6a670b0a4e4ad53822cbb',
    messagingSenderId: '183461530338',
    projectId: 'delish-go',
    authDomain: 'delish-go.firebaseapp.com',
    storageBucket: 'delish-go.appspot.com',
    measurementId: 'G-916WGYFW45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8u-1NAtQGfa9LHecHi731vWv7Zlyxsyk',
    appId: '1:183461530338:android:0fcb2ae325dce576822cbb',
    messagingSenderId: '183461530338',
    projectId: 'delish-go',
    storageBucket: 'delish-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVSCrp6QiLBIPV0aYjgOqxtgqFMJoO3No',
    appId: '1:183461530338:ios:2e01508bc3c7d1db822cbb',
    messagingSenderId: '183461530338',
    projectId: 'delish-go',
    storageBucket: 'delish-go.appspot.com',
    iosBundleId: 'com.example.delishGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVSCrp6QiLBIPV0aYjgOqxtgqFMJoO3No',
    appId: '1:183461530338:ios:2e01508bc3c7d1db822cbb',
    messagingSenderId: '183461530338',
    projectId: 'delish-go',
    storageBucket: 'delish-go.appspot.com',
    iosBundleId: 'com.example.delishGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPzCBiuyilPcOOTYu6kmscs1Qwu2GaegE',
    appId: '1:183461530338:web:26855ad2ddca3eb5822cbb',
    messagingSenderId: '183461530338',
    projectId: 'delish-go',
    authDomain: 'delish-go.firebaseapp.com',
    storageBucket: 'delish-go.appspot.com',
    measurementId: 'G-SRXCKM4BPH',
  );
}
